"""Filter NOTICES.txt to only components linked into raidio-bot.exe.

raidio-bot.exe is the Rust + Tauri application binary. It statically links the
Rust crates in src-tauri/Cargo.lock and embeds the compiled Svelte frontend
bundle (including its NPM dependencies). Everything else in the full
NOTICES.txt — ComfyUI ecosystem, Python packages, AI model weights, ffmpeg
and other system tools — ships in the separate Steam Backend depot
(AppID/Depot 4600002) and DLC depots, not inside raidio-bot.exe itself.

This tool reads sbom.json (single source of truth) and NOTICES.txt (already
enriched at release time by sbom_enrich.py), selects only the components
tagged com.raidio.depot=4600001 (the app depot), and emits
raidio-bot.exe-NOTICES.txt containing just those components in the same
plain-text format.

Usage:
    python tools/sbom_filter_exe.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SBOM_PATH = REPO_ROOT / "sbom.json"
NOTICES_PATH = REPO_ROOT / "NOTICES.txt"
OUTPUT_PATH = REPO_ROOT / "raidio-bot.exe-NOTICES.txt"

APP_DEPOT = "4600001"
DELIMITER = "═" * 75


def get_property(component: dict, name: str) -> str | None:
    """Return the value of a CycloneDX property by name, or None."""
    for prop in component.get("properties", []):
        if prop.get("name") == name:
            return prop.get("value")
    return None


def main() -> int:
    sbom = json.loads(SBOM_PATH.read_text(encoding="utf-8"))

    selected: set[tuple[str, str]] = set()
    for c in sbom.get("components", []):
        if get_property(c, "com.raidio.depot") != APP_DEPOT:
            continue
        name = c.get("name", "")
        version = c.get("version", "")
        if not name or not version:
            continue
        selected.add((name, version))

    if not selected:
        print("ERROR: no depot-4600001 components found in sbom.json")
        return 1

    notices = NOTICES_PATH.read_text(encoding="utf-8")
    blocks = notices.split(DELIMITER)

    if len(blocks) < 3:
        print(f"ERROR: NOTICES.txt only had {len(blocks)} sections — unexpected")
        return 1

    selected_blocks: list[str] = []
    for block in blocks:
        first_line = next(
            (ln for ln in block.splitlines() if ln.startswith("COMPONENT:")),
            None,
        )
        if first_line is None:
            continue
        header = first_line[len("COMPONENT:") :].strip()
        parts = header.rsplit(" ", 1)
        if len(parts) != 2:
            continue
        name, version = parts[0].strip(), parts[1].strip()
        if (name, version) in selected:
            selected_blocks.append(block)

    component_lines = []
    for block in selected_blocks:
        for ln in block.splitlines():
            if ln.startswith("COMPONENT:"):
                component_lines.append(ln[len("COMPONENT:") :].strip())
                break

    header_lines = [
        "rAIdio.bot — raidio-bot.exe Third-Party Notices",
        "",
        "Notices for the Rust + Tauri application binary (raidio-bot.exe).",
        "This file is a strict subset of NOTICES.txt covering only the",
        "components statically linked into the executable: Rust crates",
        "(Cargo dependencies) and the bundled Svelte frontend (NPM",
        "dependencies, embedded into the binary at build time).",
        "",
        "Components shipped in other Steam depots — ComfyUI ecosystem,",
        "Python packages, AI model weights, ffmpeg and other system tools —",
        "are documented in the full NOTICES.txt in this same repository.",
        "",
        f"Generated by tools/sbom_filter_exe.py from sbom.json. "
        f"Selection criterion: com.raidio.depot = {APP_DEPOT}.",
        "",
        DELIMITER,
        "TABLE OF CONTENTS",
        "─" * 75,
        f"Total components: {len(selected_blocks)}. Alphabetical by name.",
        "",
    ]
    for cl in sorted(component_lines, key=lambda s: s.lower()):
        header_lines.append(f"  {cl}")
    header_lines.append("")

    output = "\n".join(header_lines) + DELIMITER + DELIMITER.join(selected_blocks)
    OUTPUT_PATH.write_text(output, encoding="utf-8")

    print(
        f"Wrote {OUTPUT_PATH.name}: "
        f"{len(selected_blocks)} components / {len(selected)} expected "
        f"(diff = {len(selected) - len(selected_blocks)})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
